### ISSUE TITLE
Can't compile on Arch Linux

### ISSUE THREAD

**Issue by daphniz** [purdeaandrei/ibm_capsense_usb_mods#1]
util % make
		compiling src/ColSkips.cpp
		In file included from /usr/include/c++/9.3.0/bits/stl_algo.h:59,
						 from /usr/include/c++/9.3.0/algorithm:62,
						 from /usr/include/qt/QtCore/qglobal.h:142,
						 from /usr/include/qt/QtGui/qtguiglobal.h:43,
						 from /usr/include/qt/QtWidgets/qtwidgetsglobal.h:43,
						 from /usr/include/qt/QtWidgets/qcheckbox.h:43,
						 from /usr/include/qt/QtWidgets/QCheckBox:1,
						 from src/ColSkips.h:20,
						 from src/ColSkips.cpp:17:
		/usr/include/c++/9.3.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
		   75 | #include_next <stdlib.h>
			  |               ^~~~~~~~~~
		compilation terminated.
		make: *** [Makefile:1056: .build/ColSkips.o] Error 1
		util 2 %

**Comment by purdeaandrei** [comment]
There you go:
https://github.com/purdeaandrei/ibm_capsense_usb_mods/commit/2d4aa9dab2ccf1bd019305347d499b9ae29ecf90
